[toolchain]
# https://rust-lang.github.io/rustup-components-history/
channel = "1.98.1"
components = ["rustfmt", "cargo", "clippy", "rust-analyzer", "llvm-tools"]
profile = "default"
targets = ["wasm32-unknown-unknown"]
